env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: 'latest'
plugins:
  - react
  - simple-import-sort
  - import
rules:
  'max-len':
    - error
    - code: 120
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never

  'simple-import-sort/imports': 'error'
  'simple-import-sort/exports': 'error'
  'import/first': 'error'
  'import/newline-after-import': 'error'
  'import/no-duplicates': 'error'

  'react/react-in-jsx-scope': 0
  'react/jsx-uses-react': 0
  'react/prop-types': 0
  'react/display-name': 0
  'react/no-children-prop': 0
