const OrdersActionType = {
  GET_DETAIL_COMPLAINT_START: 'GET_DETAIL_COMPLAINT_START',
  GET_DETAIL_COMPLAINT_SUCCESS: 'GET_DETAIL_COMPLAINT_SUCCESS',
  GET_DETAIL_COMPLAINT_FAILURE: 'GET_DETAIL_COMPLAINT_FAILURE',

  GET_COMPLAINTS_START: 'GET_COMPLAINTS_START',
  GET_COMPLAINTS_SUCCESS: 'GET_COMPLAINTS_SUCCESS',
  GET_COMPLAINTS_FAILURE: 'GET_COMPLAINTS_FAILURE',

  INSERT_COMPLAINT_START: 'INSERT_COMPLAINT_START',
  INSERT_COMPLAINT_SUCCESS: 'INSERT_COMPLAINT_SUCCESS',
  INSERT_COMPLAINT_FAILURE: 'INSERT_COMPLAINT_FAILURE',

  MERGE_COMPLAINT_START: 'MERGE_COMPLAINT_START',
  MERGE_COMPLAINT_SUCCESS: 'MERGE_COMPLAINT_SUCCESS',
  MERGE_COMPLAINT_FAILURE: 'MERGE_COMPLAINT_FAILURE',
}
  
export default OrdersActionType