const DeliveryTypes = {
  CREATE_DELIVERY_START: 'FETCH_ORDERS_START',
  CREATE_DELIVERY_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  CREATE_DELIVERY_FAILURE: 'FETCH_ORDERS_FAILURE',
}

export default DeliveryTypes