const OrdersActionType = {
  ADD_SALE_PRODUCT: 'ADD_SALE_PRODUCT',

  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',

  FETCH_ORDER_BY_ID_START: 'FETCH_ORDER_BY_ID_START',
  FETCH_ORDER_BY_ID_SUCCESS: 'FETCH_ORDER_BY_ID_SUCCESS',
  FETCH_ORDER_BY_ID_FAILURE: 'FETCH_ORDER_BY_ID_FAILURE',

  FETCH_GOODTYPES_START: 'FETCH_GOODTYPES_START',
  FETCH_GOODTYPES_SUCCESS: 'FETCH_GOODTYPES_SUCCESS',
  FETCH_GOODTYPES_FAILURE: 'FETCH_GOODTYPES_FAILURE',

  FETCH_ORDERS_SYSTEM_LIST_START: 'FETCH_ORDERS_SYSTEM_LIST_START',
  FETCH_ORDERS_SYSTEM_LIST_SUCCESS: 'FETCH_ORDERS_SYSTEM_LIST_SUCCESS',
  FETCH_ORDERS_SYSTEM_LIST_FAILURE: 'FETCH_ORDERS_SYSTEM_LIST_FAILURE',

  FETCH_SUPPLIERS_BY_PAGE_START: 'FETCH_SUPPLIERS_BY_PAGE_START',
  FETCH_SUPPLIERS_BY_PAGE_SUCCESS: 'FETCH_SUPPLIERS_BY_PAGE_SUCCESS',
  FETCH_SUPPLIERS_BY_PAGE_FAILURE: 'FETCH_SUPPLIERS_BY_PAGE_FAILURE',

  FETCH_STUFF_TYPES_START: 'FETCH_STUFF_TYPES_START',
  FETCH_STUFF_TYPES_SUCCESS: 'FETCH_STUFF_TYPES_SUCCESS',
  FETCH_STUFF_TYPES_FAILURE: 'FETCH_STUFF_TYPES_FAILURE',

  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

  UPDATE_ORDER_START: 'UPDATE_ORDER_START',
  UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
  UPDATE_ORDER_FAILURE: 'UPDATE_ORDER_FAILURE',

  DELETE_ORDER_START: 'DELETE_ORDER_START',
  DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
  DELETE_ORDER_FAILURE: 'DELETE_ORDER_FAILURE',
}

export default OrdersActionType